# Generated by Django 4.1.3 on 2023-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipay', '0003_alter_usersbalance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbalance',
            name='currency',
            field=models.CharField(choices=[('$', 'Usd'), ('N', 'Naira'), ('PKR', 'Pakistani Rupee'), ('GHS', 'Ghanaian Cedis')], default='N', editable=False, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='usersbalance',
            constraint=models.CheckConstraint(check=models.Q(('currency__in', ['$', 'N', 'PKR', 'GHS'])), name='pipay_usersbalance_currency_valid'),
        ),
    ]
