# Generated by Django 4.1.3 on 2023-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipay', '0004_alter_usersbalance_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbalance',
            name='currency',
            field=models.CharField(choices=[('$', 'Usd'), ('N', 'Naira'), ('PKR', 'Pakistani Rupee'), ('GHS', 'Ghanaian Cedis')], default='$', editable=False, max_length=50),
        ),
    ]
