# Generated by Django 4.1.3 on 2023-05-26 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipay', '0005_alter_usersbalance_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatecode',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatecode',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
