# Generated by Django 4.1.3 on 2023-05-28 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipay', '0006_generatecode_generated_by_generatecode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbalance',
            name='currency',
            field=models.CharField(choices=[('$', 'Usd'), ('N', 'Naira'), ('PKR', 'Pakistani Rupee'), ('GHS', 'Ghanaian Cedis')], default='N', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersbalance',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_currency', to=settings.AUTH_USER_MODEL),
        ),
    ]
