# Generated by Django 4.1.3 on 2023-07-17 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipay', '0008_remove_usersbalance_pipay_usersbalance_currency_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbalance',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_currency', to=settings.AUTH_USER_MODEL),
        ),
    ]
