# Generated by Django 4.1.3 on 2023-07-20 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipay', '0009_alter_usersbalance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoginTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_completed', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
