# Generated by Django 4.1.3 on 2023-10-19 19:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipay", "0011_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("bank_name", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("transaction_id", models.CharField(max_length=12, unique=True)),
                (
                    "withdrawal_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date withdraw"
                    ),
                ),
                ("save_info", models.BooleanField(default=True)),
                ("account_balance", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=6000.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(6000.0)],
                    ),
                ),
                ("transaction_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_withdraw",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
