# Generated by Django 4.1.3 on 2023-10-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipay", "0012_withdraw"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_link", models.URLField(blank=True)),
                ("task_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
