# Generated by Django 4.1.3 on 2023-10-23 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipay", "0015_advertpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersbalance",
            name="affilate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="usersbalance",
            name="task",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="usersbalance",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_currency",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
