# Generated by Django 4.1.3 on 2023-10-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipay", "0016_alter_usersbalance_affilate_alter_usersbalance_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdraw",
            name="account_number",
            field=models.CharField(default="xxxxxx9309", max_length=50),
        ),
    ]
