# Generated by Django 4.1.3 on 2023-10-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipay', '0017_withdraw_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecode',
            name='coupon_code',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
