# Generated by Django 4.1.3 on 2023-10-27 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pipay", "0018_alter_generatecode_coupon_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraw",
            name="bank_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="email",
            field=models.EmailField(max_length=60, null=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_withdraw",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
