# Generated by Django 4.1.3 on 2023-11-16 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipay", "0020_advertpost_description_advertpost_embed_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="withdraw",
            options={"ordering": ["withdrawal_date"]},
        ),
    ]
