# Generated by Django 4.1.3 on 2023-11-01 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveWithdrawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=60, null=True, verbose_name="email"),
                ),
                ("bank_name", models.CharField(max_length=100, null=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "account_number",
                    models.CharField(default="xxxxxx9309", max_length=50),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_save_withdraw",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
