# Generated by Django 4.1.3 on 2023-07-28 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userreferrallink_level_userreferrallink_lft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL)),
                ('user_list', models.ManyToManyField(related_name='referral_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserReferralLink',
        ),
    ]
