# Generated by Django 4.1.3 on 2023-10-12 15:24

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_referrallist_delete_userreferrallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to=user.utils.image_location),
        ),
    ]
