# Generated by Django 4.1.3 on 2023-10-13 20:16

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=user.utils.image_location),
        ),
    ]
