# Generated by Django 4.1.3 on 2023-10-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
